[workspace]
exclude = ["a32nx"]
resolver = "2"

members = [
    "build-su95x/src/wasm/systems/a320_systems",
    "build-su95x/src/wasm/systems/a320_systems_wasm",
    "build-su95x/src/wasm/systems/a320_hydraulic_simulation_graphs",
    "build-su95x-common/src/wasm/systems/systems",
    "build-su95x-common/src/wasm/systems/systems_wasm",
]

[profile.release]
lto = true
strip = true

[profile.test]
# We enable some basic optimization to prevent stack overflows during testing (flybywiresim/a32nx#7631)
# However, if this interferes with your ability to debug locally you can disable it here
opt-level=1
lto = false
debug-assertions=true
debug=true
