name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      MAIN_PRE_RELEASE_ID: 64726828
      MAIN_PRE_RELEASE_TAG: vmain
      MAIN_ZIP_NAME: headwind-aircraft-a330-900-main.zip
      BUILD_DIR_NAME: vmain
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
      - name: Copy Sources
        run: |
          ./scripts/dev-env/run.sh ./scripts/copy.sh
      - name: Build A339X Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build.sh --no-tty -j 4
      - name: Build ZIP file
        run: |
          mkdir ./${{ env.BUILD_DIR_NAME }}
          zip -r ./${{ env.BUILD_DIR_NAME }}/${{ env.MAIN_ZIP_NAME }} ./headwind-aircraft-a330-900/
      - name: Build fragments
        run: |
          ./scripts/dev-env/run.sh node ./scripts/fragment.js
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.MAIN_PRE_RELEASE_TAG }}
          assets: '*'
      - name: Upload main zip asset to vmain release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.MAIN_PRE_RELEASE_ID }}/assets{?name,label}
          asset_path: ./${{ env.BUILD_DIR_NAME }}/${{ env.MAIN_ZIP_NAME }}
          asset_name: ${{ env.MAIN_ZIP_NAME }}
          asset_content_type: application/zip
      - name: Upload fragment assets to vmain release
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_id: ${{ env.MAIN_PRE_RELEASE_ID }}
          assets_path: ./build-modules/
      - name: Update vmain release body
        run: |
          curl --request PATCH \
            --url 'https://api.github.com/repos/${{ github.repository }}/releases/${{ env.MAIN_PRE_RELEASE_ID }}' \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "body": "This release has its asset updated on every commit to the main branch\nLast updated on ${{ env.BUILT_DATE_TIME }} from commit ${{ github.sha }}\nThis link will always point to the latest main build: https://github.com/${{ github.repository }}/releases/download/${{ env.MAIN_PRE_RELEASE_TAG }}/${{ env.MAIN_ZIP_NAME }}"
            }'
